name: qolber_clean_arc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^7.7.0
  dartz: ^0.10.1
  logger: ^2.0.2
  firebase_core: ^3.0.0
  cloud_firestore: ^5.6.11
  firebase_auth:
  firebase_storage: ^12.0.4
  bloc: ^8.1.2
  animate_do: ^3.1.2
  flutter_bloc: ^8.1.6
  flutter_spinkit: ^5.1.0
  file_picker:
  cached_network_image:



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
